### ISSUE TITLE
Extract markdownit module

### ISSUE THREAD

**Issue by Geminii** [nuxt-community/community-modules#392]
Extract markdownit module : 

- [x] add PR for this on : https://github.com/nuxt-community/markdownit-module/pull/23
- [x] add documentation single layout
- [x] add test on the module

**Comment by pi0** [comment]
Module is already extracted into [nuxt-community/markdownit-module](https://github.com/nuxt-community/markdownit-module) (preserving previous contributions. Would you please open a PR to update repo? (the ones here should be eventually removed)

**Comment by Geminii** [comment]
> Module is already extracted into [nuxt-community/markdownit-module](https://github.com/nuxt-community/markdownit-module) (preserving previous contributions). Would you please open a PR to update repo? (the ones here should be eventually removed)

You're right, I didn't see that it already existed because I could have proposed a PR directly in this repo. 
Thanks to point it. I will update this issue and associate a PR.
