### ISSUE TITLE
Extract yandex-metrika module

### ISSUE THREAD

**Issue by Geminii** [nuxt-community/community-modules#394]
This module is already extract to `nuxt-community` (https://github.com/nuxt-community/yandex-metrika-module)
I will update link from `awesome-nuxt` & `modules.nuxtjs.org` to uniformize again 😀

- `awesome-nuxt` (https://github.com/nuxt-community/awesome-nuxt/pull/439)
- `modules.nuxtjs.org` (https://github.com/nuxt/modules/pull/78)

**Comment by pi0** [comment]
Thanks @Geminii. Would you please also make a PR to this repo for removing code?

**Comment by Geminii** [comment]
Yes i already did it here no ? [https://github.com/nuxt-community/community-modules/pull/395](url)

**Comment by pi0** [comment]
Oh sorry I missed it 👍
