### ISSUE TITLE
Extract bulma-module

### ISSUE THREAD

**Issue by Geminii** [nuxt-community/community-modules#398]
I don't find any repository on `nuxt-community/bulma-module`

Tasks : 
- [x] extract the module (https://github.com/Geminii/bulma-module)
- [x] reorganize module
- [x] add `nuxt/test-utils`
- [x] add eslint
- [x] add example
- [ ] transfer into `nuxt-community` repo
- [ ] update awesome-nuxt bulma module link
- [ ] update `modules.nuxtjs.org` bulma module link
- [x] create a PR to remove `bulma` into this repository (https://github.com/nuxt-community/community-modules/pull/399)

@pi0 @Atinux

**Comment by Geminii** [comment]
> I am wondering if this is required since it is only adding a CSS file 🤔

Yes for the moment, this module only include a css file but maybe we can evolve the module ? Add some configurations or other ? Dunno if there is an interest about it?

> Also, buefy is doing a great job and has a Nuxt installation: https://buefy.org/documentation/start#nuxtjs

Buefy is based on Bulma and there is already a module for it (https://github.com/buefy/nuxt-buefy). 
If a developper want to only include Bulma without Buefy addons, do you think in this case that Buefy need to be include in this context ?

**Comment by pi0** [comment]
Fully agree. With buefiy, this module doesn't makes sense anymore and should be deprecated. Also made issue for CNA removal: https://github.com/nuxt/create-nuxt-app/issues/694

**Comment by Geminii** [comment]
Ok in this way, i will remove the bulma-module. It make no sense to keep it 😅
