### ISSUE TITLE
toast ssr problem

### ISSUE THREAD

**Issue by productfrontenddeveloper** [nuxt-community/community-modules#404]
<img width="1380" alt="Screen Shot 2021-02-26 at 16 22 45" src="https://user-images.githubusercontent.com/38668796/109305515-e209b000-784e-11eb-9a75-1c7d0e0a44c7.png">

```modules: [
    // https://go.nuxtjs.dev/axios
    '@nuxtjs/axios',
    // https://go.nuxtjs.dev/pwa
    '@nuxtjs/pwa',
    // https://go.nuxtjs.dev/content
    // '@nuxt/content',
    '@nuxtjs/auth-next',
    '@nuxtjs/toast',
    '@nuxtjs/proxy',
    [
      'nuxt-i18n',```

**Comment by pi0** [comment]
@productfrontenddeveloper is this issue reported for vite module?

**Comment by productfrontenddeveloper** [comment]
no, I didn't know where to write but this error comes with vite.

**Comment by pi0** [comment]
Vite is not an official bundler for nuxt2. We can track by nuxt/vite#25
