### ISSUE TITLE
@nuxtjs/toast => Cannot read property 'show' of undefined

### ISSUE THREAD

**Issue by miladfathi021** [nuxt-community/community-modules#406]
TypeError
Cannot read property 'show' of undefined

usage:
this.$toast.show('Logging in...')

tsconfig.json: 
"types": [
      "@nuxtjs/toast"
    ]

nuxt.config.js:
modules: [
    '@nuxtjs/toast'
  ],

  toast: {
    position: 'bottom-left'
  },

**Comment by jgrandar** [comment]
Same here

**Comment by parthdevloper** [comment]
+1
